title: A Sublime Dive into Gemini CLI
description: Master Gemini CLI using Sublime Text

# Theme configuration
remote_theme: just-the-docs/just-the-docs

# Enable search
search_enabled: true
search:
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Navigation configuration
aux_links:
  "Gemini CLI on GitHub":
    - https://github.com/flashmodel/sublime-gemini-book

# Footer content
footer_content: "Copyright &copy; 2024 flashmodel. Distributed by an MIT license."

# Just the Docs specific settings
heading_anchors: true
